details:
  name: Fundamentals
  repository_name: unit-fundamentals

sequence:
############################################################
#               SPRINT 1
############################################################
  Core JavaScript:
    - name: Unit 1 Launch
      elements:
        - kind: deck
        - kind: recording
    - name: Introduction to Algorithms # Block 1
      pursuit_path: intro-to-algorithms
      kind: lesson
      activity: canvas_text
      activity_description: "<p>To complete this lab, you will need to write an algorithm in plain language. You will not need to write any code to complete this Lab.</p>

      <p>Write an algorithm that achieves the following outcome: looking up a word in an online or physical dictionary. Keep in mind any inputs a person may need and the desired output. Additionally, focus on designing for the default scenario (i.e. 'happy path') before thinking about edge cases. If there are any edge cases you think are important to keep in mind, include them at the end.</p>

      <p>Do not spend more than 30 - 45 minutes on this Lab.</p>"
    - name: Core Tools Setup  # Block 1
      elements:
        - kind: guide
          pursuit_path: computer-setup
          pursuit_subpath: core-tools
        - kind: recording
    - name: Replit Setup  # Block 1
      elements:
        - kind: guide
          pursuit_path: external-tools
          pursuit_subpath: replit
        - kind: recording
    - name: Introduction to JavaScript  # Block 2
      pursuit_path: intro-to-javascript
      kind: lesson
      activity: replit
    - name: Control Flow  # Block 3
      pursuit_path: control-flow
      kind: lesson
      activity: replit
    - name: Loops  # Block 4
      pursuit_path: loops
      kind: lesson
      activity: replit
    - name: Functions  # Block 5
      pursuit_path: functions
      kind: lesson
      activity: replit
    - name: Common Errors  # Block 5
      pursuit_path: common-errors
      kind: lesson
      activity: replit
    - name: Understanding Code Challenges  # Block 6
      pursuit_path: understanding-code-challenges
      kind: lesson
      activity: replit     
    - name: Scope  # Block 6
      pursuit_path: scope
      kind: lesson
      activity: replit
    - name: Arrays  # Block 7
      pursuit_path: arrays
      kind: lesson
      activity: replit
    - name: Common Methods and Tools  # Block 8
      pursuit_path: common-methods-and-tools
      kind: lesson
      activity: replit
      # Do on first day of first project
      # Do problem two on day two
      # Do problem three on day three
    - name: Problem Solving Methodologies # Block during project
      pursuit_path: problem-solving-methodologies
      kind: lesson
      # activity: replit # No activity - project instead
    - name: Skill Sharpening
      pursuit_path: skill-sharpening
      kind: project
      activity: replit
      points_possible: 0 # TBD 186
############################################################
#               SPRINT 2
############################################################
  Problem Solving with Code:
    - name: Objects # Block 1
      pursuit_path: objects
      kind: lesson
      activity: replit
    - name: Data Representation with Code # Block 2
      pursuit_path: data-representation-with-code
      kind: lesson
      activity: replit
    - name: Looping through Arrays with Objects # Block 3
      pursuit_path: array-object-loops
      kind: lesson
      activity: replit
    - name: Modern JavaScript Features # Block 4
      pursuit_path: modern-javascript-features
      kind: lesson
      activity: replit
    - name: Evaluating Expressions # Block 5
      pursuit_path: evaluating-expressions
      kind: lesson
      activity: replit
    - name: Nested Loops # Block 6
      pursuit_path: nested-loops
      kind: lesson
      activity: replit 
    - name: Reference Types # Block 7
      pursuit_path: reference-types
      kind: lesson
      activity: replit
    - name: Accumulator Pattern # Block 8
      pursuit_path: accumulator-pattern
      kind: lesson
      activity: replit
    - name: Skill Honing
      pursuit_path: skill-honing
      kind: project
      activity: replit
      points_possible: 0
############################################################
#               SPRINT 3
############################################################
  Coding Like a Developer:
    - name: Local Environment Setup # Block 1
      elements:
        - kind: guide
          pursuit_path: computer-setup
          pursuit_subpath: local-environment
        - kind: recording
    - name: Markdown # Block 1
      pursuit_path: markdown
      kind: lesson
      activity: repository
    - name: Introduction to the Command Line # Block 2
      pursuit_path: intro-to-command-line
      kind: lesson
      activity: repository
    - name: Git # Block 3
      pursuit_path: git
      kind: lesson
      activity: repository
    - name: GitHub Setup # Block 4
      elements:
        - kind: guide
          pursuit_path: external-tools
          pursuit_subpath: github
        - kind: recording
    - name: GitHub # Block 4
      pursuit_path: github
      kind: lesson
      activity: repository
    - name: Submit GitHub Username # Block 4
      kind: task
      activity: canvas_url
      activity_description: "<p>Once you sign up for GitHub, submit the URL to your GitHub profile. It should have the following format, where 

      <code>&lt;YOUR-USERNAME&gt;</code> is replaced with your username.</p>

      <pre>https://github.com/&lt;YOUR-USERNAME&gt;</pre>

      <p>You should be able to copy and paste from the location bar in your browser.</p>"
      points_possible: 0

    - name: JavaScript on Your Machine # Block 5
      pursuit_path: javascript-on-your-machine
      kind: lesson
      activity: repository
    - name: Higher Order Functions # Block 6 
      pursuit_path: higher-order-functions
      kind: lesson
      activity: repository
    - name: Higher Order Native Array Methods # Block 7 
      pursuit_path: higher-order-native-array-methods
      kind: lesson
      activity: repository
    - name: Dinosaur Museum
      pursuit_path: dinosaur-museum
      kind: project
      activity: repository
      points_possible: 0 # tbd
    - name: End of Module Reflection
      elements:
        - kind: deck
        - kind: recording